
# Site settings
title: Suhas Bharadwaj
name: Suhas Bharadwaj
subtitle: Learnings, Ramblings and Rants
email: suhaspbharadwaj@gmail.com
description: >
  A personal website about technical things I find useful. Also, random ramblings and rants.
baseurl: ""
url: "https://suhas-p-bharadwaj.github.io/"
twitter_username: Suhas_dude
github_username:  suhas-p-bharadwaj
disqus_baseurl: "https://suhasramblings.github.io/"
disqus_shortname: suhasramblings
permalink: :title
cover: "/assets/header_image.jpg"
logo: "/assets/nr-logo.jpg"
ga_tracking_id: "UA-126679534-1"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Suhas Bharadwaj"


# External gems
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

exclude:
  - "/vendor/"

# Collections
collections:
  - talks

#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts

social:
  - name: Twitter
    icon: twitter
    username: readfead
    url: https://twitter.com/readfead
    desc: Follow me on Twitter
    share: true

  - name: Quora
    icon: quora
    username: Suhas-Bharadwaj
    url: https://www.quora.com/profile/Suhas-Bharadwaj
    desc: Follow me on Quora
    share: true

  - name: GitHub
    icon: github
    username: suhas-p-bharadwaj
    url: https://github.com/suhas-p-bharadwaj
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: suhas-bharadwaj-ab06b638
    url: https://www.linkedin.com/in/suhas-bharadwaj-ab06b638/
    desc: Connect with me on LinkedIn
    share: true


# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/nr-logo.jpg"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/jpg"

    twitter_image: "/assets/nr-logo.jpg"

    os_repo: "https://github.com/nikhita/nikhita.github.io"
    os_rcs_type: "git"
    os_src: "git@github.com:nikhita.github.io.git"
